### ISSUE TITLE
大佬可否适配一下安卓7.1.1的机型 (*¯︶¯*)

### ISSUE THREAD

**Issue by ollyallen** [bit-chorus/permissionforge#1]
感谢大佬造福众生，今天无意发现此APP 如获至宝。奈何手机依旧是安卓7.1.1，只能看着其他小伙伴开心的用着。故特来求大佬在百忙之中适配一下安卓7.1.1，拜托您了！感激不尽

**Comment by bit-chorus** [comment]
最新版本已适配

**Comment by ollyallen** [comment]
😭我这怎么还是解析软件包出错呢 我快把这该屎的三星note8砸了得了
哎~可能是没有随便出门的命了 
不过还是要谢谢大佬哈 智慧的化身!

**Comment by bit-chorus** [comment]
这周之内会出稳定版的，alpha版apk好像有问题。耐心等一下吧，这个问题会修复的。

**Comment by ollyallen** [comment]
哇哦 好哒大佬 期待着~

**Comment by bit-chorus** [comment]
最近很忙，开发进度慢谅解一下哈

**Comment by ollyallen** [comment]
^-^感谢感谢 灰常感谢

**Comment by bit-chorus** [comment]
已更新，看看能用不

**Comment by ollyallen** [comment]
哇塞 可以用了 新版的界面也太好看了吧 太棒了 里边的界面也跟真的一样一样的 大赞
