### ISSUE TITLE
能否继续添加一下新的字段，二级审核字段

### ISSUE THREAD

**Issue by hechu1235** [bit-chorus/permissionforge#2]
比如我们一级导员通过以后还有一个二级:[xxxx系部领导]xx-审批通过，大佬可不可以更新加一下，

**Comment by hechu1235** [comment]
希望大佬后期更新可以加一下，🙏🏻🙏🏻🙏🏻

**Comment by hechu1235** [comment]
审批流程字段建议可以自定义生成前填写了系部领导字段生成后审批流程显示2步，没有系部领导字段添加就生成1步

**Comment by Iiiivan-droid** [comment]
请问这个怎么下呜呜呜呜呜我真的辣鸡

**Comment by bit-chorus** [comment]
> 请问这个怎么下呜呜呜呜呜我真的辣鸡

https://github.com/bit-chorus/permissionforge/releases/download/v2.0/permission-forge-v2.0.apk
