### ISSUE TITLE
求把软件填写信息的背景色去掉

### ISSUE THREAD

**Issue by Mionx-II** [bit-chorus/permissionforge#7]
憨批状态栏自动识别颜色变色很难看

**Comment by Mionx-II** [comment]
还有那个一共请假几小时我这里显示不完整，如图
![image](https://user-images.githubusercontent.com/49855013/97811208-e1ec1000-1cb3-11eb-8c84-b2f2c52d7993.png)

**Comment by bit-chorus** [comment]
变色不修复，不是问题。显示不全已修复。
